#!/bin/bash

rm -vf Test.js
fay --package fay-text --pretty --Wall --include=src Test.hs
node Test.js

echo "--------"
echo "js tests"
echo "--------"

rm -vf src/Translit/Hangeul.js JsTest-compiled.js
fay --package fay-text --pretty --Wall --strict Translit.Hangeul --library src/Translit/Hangeul.hs
cat src/Translit/Hangeul.js > JsTest-compiled.js
cat JsTest.js >> JsTest-compiled.js
node JsTest-compiled.js

echo "----------"
echo "js example"
echo "----------"

rm -vf FayTestWeb.js
fay --package fay-text,fay-jquery --pretty --Wall --include src FayTestWeb.hs
